// providers
export const GET_PROVIDERS = 'GET_PROVIDERS'
export const GET_PROVIDER = 'GET_PROVIDER'
export const ADD_PROVIDER = 'ADD_PROVIDER'
export const UPDATE_PROVIDER = 'UPDATE_PROVIDER'
export const DELETE_PROVIDER = 'DELETE_PROVIDER'
export const PROVIDER_ERROR = 'PROVIDER_ERROR'
